运营管理: "xpath==//a[contains(text(), '运营管理')]"
商旅事业部机构客户: "xpath==//a[contains(@href,'/operation/tmc/corp?businessUnit=TMC')]"
客户名称: "xpath==//input[@formcontrolname='nameLike']"
查询: "xpath==//span[contains(text(), '查询')]"
详情: "xpath==//span[contains(text(), '详情')]"

基础信息: "xpath==//div[contains(text(), '基础信息')]"
结算信息: "xpath==//div[contains(text(), '结算信息') and @class='ant-tabs-tab-btn']"
员工授信: "xpath==//div[contains(text(), '员工授信')]"
国内机票: "xpath==//div[contains(text(), '国内机票')]"
国际机票: "xpath==//div[contains(text(), '国际机票')]"
国内酒店: "xpath==//div[contains(text(), '国内酒店')]"
国际酒店: "xpath==//div[contains(text(), '国际酒店')]"
火车票: "xpath==//div[contains(text(), '火车票')]"
其他产品: "xpath==//div[contains(text(), '其他产品')]"

# 国内机票相关设置项
保险复选框: "xpath==//div[@nzalign='middle'][n]/div[2]/flight-insurance-config/form/div/div/nz-form-item/nz-form-control/div/div/label[m]/span[1]"  # 该项有 4 个复选框
自主预订赠险: "xpath==//div[@nzalign='middle'][1]/div[2]/flight-insurance-config/form/div/div/nz-form-item/nz-form-control/div/div/label[1]/span[1]"
自主预订固定购险: "xpath==//div[@nzalign='middle'][1]/div[2]/flight-insurance-config/form/div/div/nz-form-item/nz-form-control/div/div/label[2]/span[1]"
后台代订赠险: "xpath==//div[@nzalign='middle'][2]/div[2]/flight-insurance-config/form/div/div/nz-form-item/nz-form-control/div/div/label[1]/span[1]"
后台代订固定购险: "xpath==//div[@nzalign='middle'][2]/div[2]/flight-insurance-config/form/div/div/nz-form-item/nz-form-control/div/div/label[2]/span[1]"
选择自主预订保险: "xpath==//div[@nzalign='middle'][1]/div[2]/flight-insurance-config/form/div/div[2]/nz-form-item/nz-form-control/div/div/div/div/insurance-picker/input"
选择后台代订保险: "xpath==//div[@nzalign='middle'][2]/div[2]/flight-insurance-config/form/div/div[2]/nz-form-item/nz-form-control/div/div/div/div/insurance-picker/input"
选择具体保险: "xpath==//div[@class='ant-table-content']/table/tbody/tr[1]/td/span[2]/label/span/input"
确定: "xpath==//span[contains(text(), '确定')]"
保存: "xpath==//span[contains(text(), '保存')]"