商旅管理: "xpath==//a[contains(text(), '商旅管理')]"
出差设置: "xpath==//sidebar/ul[1]/li[2]/div[1]"
差旅政策: "xpath==//a[contains(text(), '差旅政策')]"
预订设置: "xpath==//button/span[contains(text(), '预订设置')]"
国内机票: "xpath==//div[contains(text(), '国内机票设置')]"
保险关闭状态: "xpath==//nz-switch[@formcontrolname='insuranceModeIsOptional']/button[@class='ant-switch']"
保险开启状态: "xpath==//nz-col[@formgroupname='currentInsuranceDetail']/.."
自愿购买保险开关: "xpath==//travel-policy-insurance-form/form/nz-form-item/nz-form-control/div/div/nz-switch/button"
保险类型: "xpath==//travel-policy-insurance-form/form/nz-row/nz-col[1]/nz-form-item/nz-form-control/div/div/input"
具体保险: "xpath==//div/table/tbody/tr[1]/td/span/label/span/input"
保险详情: "xpath==//nz-row/nz-col[@formgroupname='currentInsuranceDetail']"
确定: "xpath==//span[contains(text(), '确定')]"
默认购买: "xpath==//nz-select-item"
是: "xpath==//nz-option-item[@title='是']"
否: "xpath==//nz-option-item[@title='否']"
保存: "xpath==//span[contains(text(), '保存')]"